#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'
cookbook 'application_ruby'
cookbook 'apt'
cookbook 'user', :git => 'git://github.com/fnichol/chef-user'
cookbook 'ruby_build'
cookbook 'mysql'
cookbook 'database'
cookbook 'postgresql'
cookbook 'git'
cookbook 'simple_iptables', :git => 'git://github.com/dcrosta/cookbook-simple-iptables'
cookbook 'asterisk'
